# Use a base image compatible with Raspberry Pi
FROM arm32v7/python:3

# Set working directory
WORKDIR /app

# Copy requirements and install them
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt
RUN pip3 install --no-cache-dir smbus

# Copy your application code
COPY src/main_menu.py .
COPY src/hal ./hal/

# Command to run your application
CMD ["python", "main_menu.py"]
